
.ifndef _CHR_
    _CHR_ = 1

    .scope Chr

        SOLID_0 = $00
        SOLID_1 = $01
        SOLID_2 = $02
        SOLID_3 = $03

        EARTH_2 = $04
        EARTH_1 = $05
        EARTH_0 = $06

        ; flat
        SLOPE_0 = $07
        ; gentle up
        SLOPE_1 = $08
        SLOPE_2 = $09
        ; gentle down
        SLOPE_3 = $0A
        SLOPE_4 = $0B
        ; steep up
        SLOPE_5 = $0C
        SLOPE_6 = $0D
        ; steep down
        SLOPE_7 = $0E
        SLOPE_8 = $0F

        ; minä
        UPPER_BODY = $4B
        LOWER_BODY = $5B
        LEFT_ARM = $4C
        RIGHT_ARM = $4A

        CLOUD0 = $10
        CLOUD1 = $11
        CLOUD2 = $12
        CLOUD3 = $13
        CLOUD4 = $14
        CLOUD5 = $15
        CLOUD6 = $16
        CLOUD7 = $17

        CLOUD8  = $28
        CLOUD9  = $38
        CLOUD10 = $29
        CLOUD11 = $39
        CLOUD12 = $2a
        CLOUD13 = $3a
        CLOUD14 = $2b
        CLOUD15 = $3b
        CLOUD16 = $2c
        CLOUD17 = $3c
        CLOUD18 = $2d
        CLOUD19 = $3d
        CLOUD20 = $2e
        CLOUD21 = $3e
        CLOUD22 = $2f
        CLOUD23 = $3f
    .endscope

.endif
