; AUTO-GENERATED by tools/gen.py
.include "ppu.inc"

.export palette

.segment "RODATA"

aSpritePal:
.byte $22,$16,$0f,$28
.byte $22,$00,$0f,$10
.byte $22,$20,$10,$00
.byte $22,$2a,$28,$16

.segment "CODE"
.proc palette
    lda #>Ppu::SPRITE_PALETTE
    sta Ppu::ADDR
    sta Ppu::ADDR2
    lda #<Ppu::SPRITE_PALETTE
    sta Ppu::ADDR
    sta Ppu::ADDR2
    ldx #0
loop:
    lda aSpritePal, x
    sta Ppu::DATA
    sta Ppu::DATA2
    inx
    cpx #16
    bne loop
    rts
.endproc
