; AUTO-GENERATED by tools/gen.py

.export rbaTrainBody
.export rbaWheelDX

.segment "RODATA"

; sSprite layout: bPosY, bTile, bAttr, bPosX
rbaTrainBody:
.byte 0, $34, $00, 0
.byte 0, $35, $00, 8
.byte 0, $36, $00, 16
.byte 0, $37, $00, 24
.byte 8, $38, $00, 0
.byte 8, $39, $00, 8
.byte 8, $3a, $00, 16
.byte 8, $3b, $00, 24
.byte 16, $3c, $00, 0
.byte 16, $3d, $00, 8
.byte 16, $3e, $00, 16
.byte 16, $3f, $00, 24
TRAIN_BODY_COUNT = 12

rbaWheelDX:
.byte 5,13,21
